.github/boring-cyborg.yml
.github/workflows/ci.yml
.idea/vcs.xml
flink-connector-aws-dynamodb/pom.xml
flink-sql-connector-aws-dynamodb/pom.xml
pom.xml
tools/maven/checkstyle.xml
tools/maven/suppressions.xml

Adding the baseline project structure, Maven pom files and checkstyle configuration
* Added parent, connector and SQL connector `pom.xml` files
* Adding checkstyle config (from Flink) and empty suppressions file
- `mvn clean package` is successfull
- Dependencies (does it add or upgrade a dependency): yes

[FLINK-29246] Adding skeleton project files and checkstyle configuration

---

.github/boring-cyborg.yml
flink-connector-dynamodb/pom.xml
flink-sql-connector-dynamodb/pom.xml
pom.xml

Rename modules, remove the 'aws' tag inline with repo name
* Renamed `flink-connector-aws-dynamodb` to `flink-connector-dynamodb`
* Renamed `flink-sql-connector-aws-dynamodb` to `flink-sql-connector-dynamodb`
- `mvn clean package` is successfull
- Dependencies (does it add or upgrade a dependency): yes

[FLINK-29246] Rename modules, remove the 'aws' tag inline with repo name

---

pom.xml

Setup (fix) convergence configuration such that convergence is checked on CI
* Enable convergence check (still requires `-Pcheck-convergence` to run it)
Run locally:
* Enabled: `mvn validate -Pcheck-convergence`
* Disabled: `mvn validate`

[FLINK-29441] Setup (fix) convergence configuration

---

.github/workflows/ci.yml
pom.xml
tools/ci/log4j.properties

Added maven plugin to use in ci workflow for license check.
Note: 
- License check current runs on mvn install directory, which will need to be updated when switched to deploy mode.
- We are using flink-ci-tools dependency which is only available as SNAPSHOT at the moment. https://repository.apache.org/content/repositories/snapshots/org/apache/flink/flink-ci-tools/
Previous closed PR: https://github.com/apache/flink-connector-dynamodb/pull/8. Created new PR to update branch to pull from.

[FLINK-29310] Added license check

---

.github/workflows/ci.yml

This is a hotfix for build failure caused by typo in yaml multiline literal.

[FLINK-29896] hotfix for build failure due to yaml literal typo

---

flink-connector-dynamodb/pom.xml
flink-sql-connector-dynamodb/pom.xml
pom.xml

Migrate DynamoDB parent pom to AWS connectors
* Rename module name and SCM references
Full build locally

[FLINK-29905][Connectors/AWS] Migrate DynamoDB parent pom 

---

flink-connector-dynamodb/pom.xml
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDBEnhancedElementConverter.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDBEnhancedElementConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/SinkIntoDynamoDb.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/SinkIntoDynamoDbUsingEnhancedElementConverter.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/Order.java
flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE

Add an `ElementConverter` based on the dynamodb-enhanced client.
* Added a new Element Converter `DynamoDBEnhancedElementConverter`
* Add sample job
* Added unit test
* Updated NOTICE file
Run locally and persisted rows to DynamoDB
- Dependencies (does it add or upgrade a dependency): yes
- If yes, how is the feature documented? will follow up

[FLINK-29937][Connectors/DynamoDB] Enhanced DynamoDB Element Converter

---

flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbBeanElementConverter.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbBeanElementConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/SinkDynamoDbBeanIntoDynamoDb.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/Order.java

Rename `DynamoDBEnhancedElementConverter` to `DynamoDbBeanElementConverter` and general tidy
- Rename `DynamoDBEnhancedElementConverter` to `DynamoDbBeanElementConverter`
- Update sample application
- Fix/improve comments and javadoc
- Add missing `@PublicEvolving`
Run `SinkDynamoDbBeanIntoDynamoDb` locally

[FLINK-29937][Connectors/DynamoDB] Rename DynamoDBEnhancedElementConverter

---

.github/workflows/ci.yml
.gitmodules
flink-connector-dynamodb/pom.xml
flink-sql-connector-dynamodb/pom.xml
pom.xml

Add support for Flink 1.16
* Set default Flink version to 1.16.0
* Remove snapshot repo
* Add CI build profile for 1.16.0
* Syncing parent pom to elasticsearch in prep for release
* Adding git submodule for connector release scripts
Run locally
- Dependencies (does it add or upgrade a dependency): yes

[FLINK-30008][Connectors/AWS] Upgrade to Flink 1.16.0 and add CI build

---

flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/util/PrimaryKeyBuilder.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/DynamoDbSerializationUtilTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/PrimaryKeyBuilderTest.java

Migrate DynamoDb unit tests to JUnit5
Ran unit tests locally and verified all passed.
* Dependencies (does it add or upgrade a dependency): no
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
* The serializers: no
* The runtime per-record code paths (performance sensitive): no
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
* The S3 file system connector: no
* Does this pull request introduce a new feature? no
* If yes, how is the feature documented? n/a

[FLINK-30098] Migrate DynamoDb unit tests to JUnit5

---

flink-connector-dynamodb/pom.xml
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbConfiguration.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbConnectorOptions.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSink.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactory.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/RowDataElementConverter.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverter.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/converter/ArrayAttributeConverter.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/converter/ArrayAttributeConverterProvider.java
flink-connector-dynamodb/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/example_dynamodb.sql
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/example_dynamodb_static_partitions.sql
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactoryTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataElementConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/converter/ArrayAttributeConverterTest.java
flink-sql-connector-dynamodb/pom.xml
flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
flink-sql-connector-dynamodb/src/main/resources/org/apache/flink/connector/dynamodb/shaded/software/amazon/awssdk/services/dynamodb/execution.interceptors

- Implement Table API for DynamoDB sink
* Note that the support for Doubles is not great at the moment. The Java limitations for Double is more permissive than the DDB limitation for the number type. This means that if a user writes a record with any field of DOUBLE value larger than permitted by DynamoDB, the record will fail to write.
We will followup with [FLINK-30092](https://issues.apache.org/jira/browse/FLINK-30092) to improve the experience here.
* Dependencies (does it add or upgrade a dependency): yes, table API
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
* The serializers: yes
* The runtime per-record code paths (performance sensitive): yes
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, …

[FLINK-29900][Connectors/DynamoDB] Implement Table API for DynamoDB sink

---

flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSink.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriter.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriteRequest.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/client/DynamoDbAsyncClientProvider.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/client/SdkClientProvider.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriteRequestTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriterStateSerializerTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataElementConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/DynamoDbSerializationUtilTest.java

- Further increased test coverage for DynamoDbSink
- Refactor DynamoDbSinkWriter to provide the client via constructor so that we can test logic in `DynamoDbSinkWriter` without relying on an IT case.
- Built locally with unit and integration tests. Both pass
- Manually tested datastream and Table API using examples provided.
* Dependencies (does it add or upgrade a dependency): no
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
* The serializers: no
* The runtime per-record code paths (performance sensitive): no
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
* The S3 file system connector: no
* Does this pull request introduce a new feature? no
* If yes, how is the feature …

[FLINK-29895] Further increase unit test coverage for DynamoDbSink

---

.github/workflows/ci.yml
flink-connector-aws-e2e-tests/README.md
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/src/test/java/org/apache/flink/connector/firehose/table/test/KinesisFirehoseTableITTest.java
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/src/test/resources/log4j2-test.properties
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/src/test/resources/send-orders.sql
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/src/test/java/org/apache/flink/connector/kinesis/table/test/KinesisStreamsTableApiIT.java
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/src/test/resources/log4j2-test.properties
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/src/test/resources/send-orders.sql
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/CustomWatermarkExtractor.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/Event.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/EventSchema.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExample.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExampleTest.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/main/java/org/apache/flink/streaming/kinesis/test/RollingAdditionMapper.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/java/org/apache/flink/streaming/kinesis/test/KinesisTableApiITCase.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/java/org/apache/flink/streaming/kinesis/test/model/Order.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/resources/filter-large-orders.sql
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/resources/log4j2-test.properties
flink-connector-aws-e2e-tests/pom.xml
pom.xml

Externalized the following modules from Flink:
- [flink-end-to-end-tests-aws-kinesis-firehose](https://github.com/apache/flink/tree/master/flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose)
- [flink-end-to-end-tests-aws-kinesis-streams](https://github.com/apache/flink/tree/master/flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams)
- [flink-streaming-kinesis-test](https://github.com/apache/flink/tree/master/flink-end-to-end-tests/flink-streaming-kinesis-test)
Update CI to run e2e tests in a separate phase.
Added an e2e tests parent for common config

[FLINK-29908] Externalize and configure E2E tests for Firehose/Kinesis connectors

---

.github/workflows/common.yml
.github/workflows/nightly.yml
.github/workflows/push_pr.yml
README.md

- Extracted existing build logic into common reusable workflow
- Added nightly build against SNAPSHOT versions of Flink
- Update actions to address Node 12 actions deprecation notice:
- `actions/checkout` to `v3`
- `actions/setup-java` to `v3`
- `stCarolas/setup-maven` to `v4.5`

[FLINK-30762][ci] Add nightly build workflow

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a pull request template.
- If yes, how is the feature documented? not applicable

[FLINK-30783][Connectors/AWS] Add a pull request template

---

flink-connector-kinesis/src/main/resources/META-INF/NOTICE
pom.xml

Bump protobuf-java dependency to 3.21.7
- Updated version in POM
- Updated NOTICE file for `flink-connector-kinesis`

[FLINK-30806][Protobuf] Bump protobuf-java dependency version to 3.21.7

---

flink-connector-aws-e2e-tests/README.md

*The `README.md` in e2e-test module uses `flink-1.16.0` as an example, but with the release of `flink`, it no longer exists(replaced by 1.16.1). Maybe we should change it to a more general form instead of updating it every time with the release of `flink`.*
- [] Dependencies have been added or upgraded
- [] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [] Serializers have been changed
- [] New feature has been introduced

[hotfix] Fix dead link in e2e-test module's README.md.

---

docs/content.zh/docs/connectors/table/kinesis.md
docs/content/docs/connectors/table/kinesis.md
flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/table/KinesisConnectorOptions.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/DefaultShardAssignerFactory.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisDynamicShardAssignerFactory.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisDynamicSource.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisDynamicTableFactory.java
flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/UniformShardAssignerFactory.java
flink-connector-kinesis/src/main/resources/META-INF/services/org.apache.flink.streaming.connectors.kinesis.table.KinesisDynamicShardAssignerFactory
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/DynamoDBStreamsDataFetcherTest.java
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisDynamicTableFactoryTest.java
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java

This pull request allows users of the Kinesis Table API Flink Connector to select from a list of shard assigner.
Added unit tests
*(Please check any boxes [x] if the answer is "yes" )*

[FLINK-30777] [Connectors/Kinesis] Allow Kinesis Table API Connector to specify shard assigner

---

flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyTest.java

We let these exceptions go up the call stack without logging them. This causes these exceptions from the Kinesis connector to be not visible to customers in their logs, despite their visibility in the exceptions tab on Flink UI.
**Current behaviour:** Errors from `getRecords` are shown under the Exceptions tab on the Flink UI. But they don't appear in customer logs.
**Desired behaviour:** Non-retriable errors from `getRecords` are logged in addition to the current behaviour.
N/A

[FLINK-16003][Connectors/Kinesis] Log non-retriable Kinesis exceptions from getRecords

---

docs/content.zh/docs/connectors/table/dynamodb.md
docs/content.zh/docs/connectors/table/firehose.md
docs/content.zh/docs/connectors/table/kinesis.md
docs/content/docs/connectors/datastream/kinesis.md
docs/content/docs/connectors/table/dynamodb.md
docs/content/docs/connectors/table/firehose.md
docs/content/docs/connectors/table/kinesis.md
flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/config/AWSConfigConstants.java
flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java

Allow users to specify custom AWS Credential Provider classes.
- Manually verified by running the Kinesis connector on a AWS KDA Studio
- Markdown docs updated
- JavaDocs

[FLINK-22828][Connectors/AWS] Configure custom AWS creds provider

---

flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
pom.xml

AWS SDK v2 from 2.19.14 to 2.20.32
Reorder NOTICE files for consistency
- [x ] Dependencies have been added or upgraded
- If yes, how is this documented? NA

[FLINK-31675][Connectors/AWS] Update AWS SDKv2 to v2.20.32 for 3.x

---

.github/workflows/push_pr.yml
docs/content/docs/connectors/datastream/kinesis.md

*backport https://github.com/apache/flink-connector-aws/pull/88 to v4.1.*
This change is a backport without tests.

[FLINK-32595][Connectors/Kinesis][backport] Fix the deserialization schema version in the datastream conneter doc

---

docs/content/docs/connectors/datastream/kinesis.md

*Fix the deserialization schema version in the datastream connecter doc.*
This change is a version change in the doc with a manual test.
- If yes, how is this documented? (not documented)

[FLINK-32595][Connectors/Kinesis] Fix the deserialization schema version in the datastream conneter doc

---

flink-connector-aws/flink-connector-aws-kinesis-firehose/archunit-violations/a6cbd99c-b115-447a-8f19-43c1094db549
flink-connector-aws/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkITCase.java
flink-connector-aws/flink-connector-aws-kinesis-streams/archunit-violations/84abeb9c-8355-4165-96aa-dda65b04e5e7
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/enumerator/KinesisStreamsSourceEnumerator.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkITCase.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/enumerator/KinesisStreamsSourceEnumeratorStateSerializerTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/enumerator/KinesisStreamsSourceEnumeratorTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/proxy/KinesisStreamProxyTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/KinesisStreamsRecordEmitterTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReaderTest.java

* [Text for ITCase MiniCluster ArchUnitTest has been changed for Flink 1.18](https://github.com/apache/flink/pull/22399). This PR removes the need for this exception violation in ITCase, by registering a local MiniCluster environment in the Firehose ITCase.
* Change in the github workflow is merely to show that this case passes against `1.18-SNAPSHOT`. It will be removed before merging.
This change is to fix breaking ArchUnitTests.

[hotfix] Add MiniClusterExtension to ITCase tests

---

flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/KinesisStateUtil.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableFlinkKinesisConsumer.java

Create KryoSerializer for SequenceNumber class explicitly to allow disabling of Generic Types via disableGenericTypes() call.
Create KinesisStateUtil class with static method createShardsStateSerializer that explicitly assigns KryoSerializer to SequenceNumber class and use this method to initialize state
Create unit test that checks for compatibility of previous TypeInformation based serializer and explicitly created KryoSerializer
Replace Mokito calls with utility MockStreamingRuntimeContext to improve testability and unify initialization method of Streaming Runtime Context
- If yes, how is this documented? (not applicable / docs / …

[FLINK-24943][Connectors / Kinesis] Explicitly create KryoSerializer for SequenceNumber class in Kinesis Consumer

---

.github/workflows/common.yml
.github/workflows/nightly.yml

* Flink nightlies are failing because the snapshots are not available to download from S3. We will temporarily swap over the tests to use the released versions because we want to test if they work, before INFRA revokes these credentials.

[hotfix][ci] Set AWS end-to-end tests to run on all push

---

.github/workflows/nightly.yml
.github/workflows/push_pr.yml

* Fix AWS end to end tests in CI build.
Verified that the secrets are pulled + AWS e2e tests run successfully in private repo.
https://github.com/hlteoh37/flink-connector-aws/actions/runs/6395003542

[hotfix][ci] Add inherited secrets to workflow

---

flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/RowDataKinesisDeserializationSchema.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/table/RowDataKinesisDeserializationSchemaTest.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/StaticValueDeserializationSchema.java

Handle null value during record deserialization in Table API with metadata fields present in source table definition.

[FLINK-33176][Connectors/Kinesis] Handle null value in RowDataKinesisDeserializationSchema

---

flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/pom.xml
flink-connector-aws/flink-sql-connector-kinesis/pom.xml
flink-connector-aws/flink-sql-connector-kinesis/src/test/java/org/apache/flink/connectors/kinesis/PackagingITCase.java

Update shading configuration for `flink-sql-connector-kinesis` to support build using Maven 3.8.6 and newer.

[FLINK-32399][Connectors/Kinesis] Update shading configuration for Kinesis SQL connector to support maven 3.8.6+

---

.github/workflows/common.yml

Prevent AWS E2E tests running on PR.
Using actions with debug logging ([docs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging))
```
##[debug]Evaluating: secrets.FLINK_AWS_USER
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'FLINK_AWS_USER'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.FLINK_AWS_PASSWORD
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'FLINK_AWS_PASSWORD'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: ((secrets.FLINK_AWS_USER != '') && …
```

[FLINK-33279][Connector/Kinesis] Skip AWS e2e tests run if credentials not present

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/table/util/KinesisStreamsConnectorOptionsUtils.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/KinesisDynamicTableSinkFactoryTest.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisConsumerOptionsUtil.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/table/KinesisDynamicTableFactoryTest.java

Allow a table can be used as a source and sink when it's defined with both consumer & producer options. The ability is achieved by not verifying an option if it's *indicated* as consumer (by `scan.` prefix) or producer (by `sink.` prefix) option when creating a source/sink based on the table definition.
Example: following table definition can be used for both source & sink operators:
```
%flink.ssql(type=update)
DROP TABLE IF EXISTS `kds_input`;
CREATE TABLE `kds_input` (
`some_string` STRING,
`some_int` BIGINT,
`time` AS PROCTIME()
) WITH (
'connector' = 'kinesis',
'stream' = 'ExampleInputStream',
'aws.region' = 'us-east-1',
'scan.stream.initpos' = 'LATEST',
'sink.fail-on-error' = 'true',
'format' = 'csv'
);
``` …

[FLINK-33181] Allow a table definition can be used to read & write data to.

---

flink-connector-aws/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-streams/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
pom.xml

Bump Guava in AWS Connectors to address CVE-2020-8908/CVE-2023-2976

[FLINK-33409][Connectors/AWS] Bump Guava in AWS Connectors to  to 32.1.3-jre

---

pom.xml

Bump Avro version in AWS Connectors to address CVE-2023-39410

[FLINK-33413][Connectors/AWS] Bump Avro version in AWS Connectors

---

docs/content.zh/docs/connectors/table/kinesis.md
docs/content/docs/connectors/table/kinesis.md
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ExceptionConfig.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/RecoverableErrorsConfig.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfiguration.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/KinesisConfigUtil.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/config/RecoverableErrorsConfigTest.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/KinesisConfigUtilTest.java

Allow users to configure a list of exceptions that will be retried indefinitely ("Recoverable Exceptions"). Applies to Fan Out consumers only, it can later be extended to other modes.
The config key is as follows:
```
flink.shard.consumer.error.recoverable[0].exception=java.net.UnknownHostException
flink.shard.consumer.error.recoverable[1].exception=java.net.SocketTimeoutException
```
This will later allow us to add (if needs be) pattern matching, for example:
```
flink.shard.consumer.error.recoverable[0].exception=java.net.SocketTimeoutException
flink.shard.consumer.error.recoverable[0].pattern="^Some Exception Message Pattern[0-9]+"
```
- ✅ Unit tests 
- ✅ Manual end to end testing: Tested only positive path. It is not easy to reproduce the negative path (i.e. make the Kinesis …

[FLINK-33260] Allow user to provide a list of recoverable exceptions

---

pom.xml

Bumping default Flink version in source to 1.17.0

[hotfix][Connectors/AWS] Bumping default Flink version in source to 1.17.0

---

docs/content.zh/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/datastream/dynamodb.md

[BP][FLINK-34017] Connectors docs with 404 link in dynamodb.md

---

flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java

Explicitly use `.builder().build()` instead of `.create()` method while constructing DefaultCredentialsProvider.
This way new instance of credentials provider will be created for each AWS SDK client to prevent failures when one of the clients closes a singleton instance, resulting in failures in others.
- *Added unit test*

[FLINK-32964][Connectors/AWS] Ensure that new instance of DefaultCredentialsProvider is created for each client

---

.idea/vcs.xml

Add instructions for Intellij on how to interpret Jira ticket ids and FLIPs.
This change allows to easily navigate from git log view in IDE to these locations.
Similar to [Flink](https://github.com/apache/flink/blob/master/.idea/vcs.xml) and [Kafka connector](https://github.com/apache/flink-connector-kafka/blob/main/.idea/vcs.xml) repos

[hotfix] Add IssueNavigationLink in Intellij VCS config

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/table/util/KinesisStreamsConnectorOptionsUtils.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/util/KinesisProducerOptionsMapperTest.java

Perform Table Options mapping on copy of Table options instead of original instance, this fixes FLINK-34044 where [Table descriptor](https://github.com/apache/flink/blob/94b55d1ae61257f21c7bb511660e7497f269abc7/flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableDescriptor.java#L70) creation of Kinesis tables passes an unmodifiable instance of map. 
- If yes, how is this documented? NA

[FLINK-34044] Copy dynamic table options before mapping deprecated configs

---

.github/workflows/common.yml
.github/workflows/nightly.yml
.github/workflows/push_pr.yml
flink-connector-aws/flink-connector-dynamodb/pom.xml
flink-connector-aws/flink-connector-kinesis/pom.xml
pom.xml

The PR adds support for jdk17, it also adds java 17 to ci build matrix
maven
This change is already covered by existing tests + java 17 added to ci

[FLINK-33506] Add support for jdk17 for AWS connectors

---

flink-connector-aws/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriter.java

Change logging level for information about records failed to be written by Kinesis and Firehose sinks from `debug` to `warn`.
Similar configuration is already in use for DynamoDB sink.

[FLINK-35269] Log information about failed records as warnings instead of debug for Kinesis and Firehose sinks

---

flink-connector-aws-base/pom.xml
flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSource.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/examples/SourceFromKinesis.java
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE

Use region provided as part of stream ARN to create Kinesis SDK client.
Unit tests.

[FLINK-35705][Connector/Kinesis] Use region from stream ARN to create Kinesis client

---

docs/content/docs/connectors/datastream/dynamodb.md
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DefaultDynamoDbElementConverter.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkBuilder.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbTypeInformedElementConverter.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DefaultDynamoDbElementConverterTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbTypeInformedElementConverterTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/ComplexPayload.java

Add `DynamoDbTypeInformedElementConverter` to convert Elements to dynamoDb Sink using its provided type Info.

[FLINK-35022][Connector/DynamoDB] Add TypeInformed DDB Element Converter as default element converter

---

.github/workflows/push_pr.yml

- Set up builds on PR to test against 1.19.1
This change is already covered by Github approval workflow.

[hotfix][ci] Update builds to test against 1.19.1

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReader.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReaderTest.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/reader/PollingDynamoDbStreamsShardSplitReader.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/reader/PollingDynamoDbStreamsShardSplitReaderTest.java

Add support for watermark alignment to FLIP-27 sources for Kinesis Data Streams and DynamoDB Streams.
- If yes, how is this documented? (not applicable / docs / JavaDocs / not documented) not applicable

[FLINK-32324][Connectors/AWS] Implement support for watermark alignment in FLIP-27 sources for KDS and DDB streams

---

flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2Util.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2UtilTest.java

Fixing retriable exception check - search both root exception and cause to determine if exception can be retried.

[FLINK-35815][Connector/Kinesis] Fix detection of recoverable exceptions for EFO operations

---

docs/content.zh/docs/connectors/datastream/sqs.md
docs/content/docs/connectors/datastream/sqs.md
flink-connector-aws-e2e-tests/flink-connector-aws-sqs-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-sqs-e2e-tests/src/test/java/org/apache/flink/connector/sqs/sink/test/SqsSinkITTest.java
flink-connector-aws-e2e-tests/flink-connector-aws-sqs-e2e-tests/src/test/resources/log4j2-test.properties
flink-connector-aws-e2e-tests/pom.xml
flink-connector-aws/flink-connector-sqs/archunit-violations/stored.rules
flink-connector-aws/flink-connector-sqs/pom.xml
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsConfigConstants.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsExceptionClassifiers.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSink.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSinkBuilder.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSinkElementConverter.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSinkException.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSinkWriter.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsStateSerializer.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/client/SdkClientProvider.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/client/SqsAsyncClientProvider.java
flink-connector-aws/flink-connector-sqs/src/main/resources/log4j2.properties
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsExceptionClassifiersTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsSinkBuilderTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsSinkElementConverterTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsSinkTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsSinkWriterTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsStateSerializerTest.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/testutils/SqsTestUtils.java
flink-connector-aws/flink-connector-sqs/src/test/resources/archunit.properties
flink-connector-aws/flink-connector-sqs/src/test/resources/log4j2-test.properties
flink-connector-aws/pom.xml

Implements the Amazon SQS Sink Connector
Added unit tests
Added integration tests
Manually verified by running the SQS connector on a local Flink cluster.

[FLINK-35305][Connector/SQS] Amazon SQS Sink Connector

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSource.java

Assist users who mistakenly provide null values to the KinesisStreamsSource by indicating which values were null. This enhances usability, as users no longer need to inspect the KinesisStreamsSource code to identify the issue when the specific null value is pointed out.
- Added the errorMessage parameter to Preconditions.checkNotNull invocations

[FLINK-36138] Add a message to KinesisStreamsSource null checks

---

flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumerator.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTracker.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTrackerTest.java

When a split is marked as finished, we are iterating over all splits and assigning available splits to readers. On a large enough stream with enough shards, we'd be spending a lot of time in finishedSplits because we are always calling `getSplitsForAssignment` function which is O(n). This leads to performance issues. Making this an O(1) algo to solve the issues
- Generally we see long checkpoint duration
- We see that the start delay is very long
- App is stuck like this for long
- We see checkpoint duration now reduced to 1second
- No more failed checkpoints due to long checkpoints
*(Please pick …

[FLINK-36270][Connectors/DynamoDB] Assign only children splits of a split when it is marked as finished

---

flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTracker.java

For stream which are always at tip and shards have not been discovered yet, we will continuously see this log, so making it a debug log
This change is already covered by existing tests
*(example:)*
- *Added integration tests for end-to-end deployment*

[FLINK-36328][Connectors/DynamoDB] Making the child split not found log as debug log instead of warn log

---

flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/testutils/AWSServicesTestUtils.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSClientUtilTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSource.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSourceITCase.java

Sets up Integrations tests for the FLIP-27 DataStreams API Kinesis source
- *Added integration tests for end-to-end deployment*

[FLINK-31986][Connectors/Kinesis] Setup integration tests for FLIP-27 Kinesis source

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReader.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSourceITCase.java

- Adds integrations test cases for multiple shards in FLIP-27 DataStreams API Kinesis source
- Fixes bug in closing assigned splits
- *Added integration tests for end-to-end deployment*

[FLINK-36427] Multiple shard IT cases for KDS source

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/PartitionKeyGenerator.java

[FLINK-36519][docs] replace accept with apply

---

flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumerator.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumeratorState.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumeratorStateSerializer.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTracker.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/util/ShardUtils.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumeratorStateSerializerTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/enumerator/DynamoDbStreamsSourceEnumeratorTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTrackerTest.java

Fixing latest behaviour for DDB Connector.
Added new unit tests

[FLINK-36523][Connectors/DynamoDB][BugFix] Fixing LATEST behaviour for DDB Connector

---

docs/content.zh/docs/connectors/table/dynamodb.md
docs/content/docs/connectors/table/dynamodb.md
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbConfiguration.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbConnectorOptions.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSink.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactory.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/RowDataElementConverter.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverter.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactoryTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverterTest.java

Add an option `ignore-nulls` to determine whether to ignore null values, instead of [hardcoding](https://github.com/maoxingda/flink-connector-aws/blob/b681cfcd372a44a34c4e6c868cb8a69d50aac67c/flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverter.java#L53) it into the code.
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
This change added tests and …

[FLINK-36428][Connectors/DynamoDB] DynamoDb Table API Sink fails when null value in the RowData

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/proxy/KinesisStreamProxy.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/proxy/KinesisStreamProxyTest.java

Fixes ListShards for Kinesis streams with large number of shards
This change is already covered by existing unit tests in `KinesisStreamProxyTest`

[FLINK-36637] Fix ListShards for large KDS streams

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSource.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSourceBuilder.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/config/KinesisSourceConfigOptions.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/enumerator/KinesisStreamsSourceEnumerator.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/proxy/AsyncStreamProxy.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/proxy/KinesisAsyncStreamProxy.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/proxy/KinesisStreamProxy.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/proxy/StreamProxy.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/KinesisShardSplitReaderBase.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/fanout/FanOutKinesisShardSplitReader.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/fanout/FanOutKinesisShardSubscription.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/fanout/StreamConsumerRegistrar.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/polling/PollingKinesisShardSplitReader.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/split/StartingPositionUtil.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/KinesisStreamsSourceITCase.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/enumerator/KinesisStreamsSourceEnumeratorTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/proxy/KinesisAsyncStreamProxyTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/KinesisStreamsSourceReaderTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReaderTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/fanout/FanOutKinesisShardSplitReaderTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/reader/fanout/StreamConsumerRegistrarTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/split/StartingPositionUtilTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/util/FakeKinesisFanOutBehaviorsFactory.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/util/KinesisAsyncClientProvider.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/util/KinesisStreamProxyProvider.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/source/util/TestUtil.java

Implement support for EFO in the new KDS source
- Manually verified by running the Kinesis connector on a local Flink cluster.
- If yes, how is this documented? Documented as part of https://issues.apache.org/jira/browse/FLINK-31989

[FLINK-31980] Implement support for EFO in Kinesis consumer

---

flink-connector-aws/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-streams/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE

Fix `NOTICE` files to reflect the dependencies packaged into the uber jar.
Validated using helpful script provided by @dannycranmer 
```
mvn clean install | grep Including | grep -v org.apache.flink | sed -E 's/\S+\s+\S+\s+(\S+).*/\1/' | sed 's/:jar//' | sed 's/.*Including \(.*\) in the shaded jar\./\1/' | sort > /tmp/from.build
cat src/main/resources/META-INF/NOTICE | grep "^\- " | sed 's/- //' | sort > /tmp/from.notice
diff /tmp/from.build /tmp/from.notice
```

[hotfix] Update NOTICE files to reflect the packaged dependencies

---

docs/content/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/datastream/kinesis.md
docs/content/docs/connectors/table/kinesis.md

Updates English docs for `KinesisStreamsSource` and `DynamoDbStreamsSource`
This change is a docs change without any test coverage.

[FLINK-31989][docs] Update english docs for KinesisStreamsSource and DynamoDbStreamsSource

---

flink-connector-aws/flink-connector-dynamodb/pom.xml
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/DynamoDbStreamsSource.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/config/DynamodbStreamsSourceConfigConstants.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/reader/PollingDynamoDbStreamsShardSplitReader.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/reader/DynamoDbStreamsSourceReaderTest.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/source/reader/PollingDynamoDbStreamsShardSplitReaderTest.java

DDB Streams customers are charged on number of getrecords calls and given the connector maintains a queue of shards and if a task manager has only a few shards in the queue, it can cause a shard being called (1000/(x*y)) times in a second where x = number of shards in the queue, y = average getrecords latency. 
We should ideally be having some delay in case the last poll was an empty poll so that the customer gets charged less 
- *Manually verified by running the Kinesis …

[FLINK-36203][Connectors/DynamoDB] Added polling delay between getrecords calls

---

.github/workflows/nightly.yml
.github/workflows/push_pr.yml
flink-connector-aws/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriter.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriter.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
flink-connector-aws/flink-connector-sqs/src/main/java/org/apache/flink/connector/sqs/sink/SqsSinkWriter.java
flink-connector-aws/flink-connector-sqs/src/test/java/org/apache/flink/connector/sqs/sink/SqsSinkWriterTest.java
pom.xml

- Move `submitRequestEntries` implementation for AWS sinks to use `ResultHandler`
- Bump flink version to 1.20
- Adapt pipelines to Flink version change
This change is already covered by existing sink unit tests

[FLINK-36770][Connectors/AWS]  make AWS sink writers use ResultHandler, move flink version to 1.20

---

.github/workflows/common.yml
flink-connector-aws-e2e-tests/flink-formats-avro-glue-schema-registry-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-formats-avro-glue-schema-registry-e2e-tests/src/test/java/org/apache/flink/glue/schema/registry/test/GSRKinesisPubsubClient.java
flink-connector-aws-e2e-tests/flink-formats-avro-glue-schema-registry-e2e-tests/src/test/java/org/apache/flink/glue/schema/registry/test/GlueSchemaRegistryAvroKinesisITCase.java
flink-connector-aws-e2e-tests/flink-formats-json-glue-schema-registry-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-formats-json-glue-schema-registry-e2e-tests/src/test/java/org/apache/flink/glue/schema/registry/test/json/GSRKinesisPubsubClient.java
flink-connector-aws-e2e-tests/flink-formats-json-glue-schema-registry-e2e-tests/src/test/java/org/apache/flink/glue/schema/registry/test/json/GlueSchemaRegistryJsonKinesisITCase.java
flink-connector-aws-e2e-tests/pom.xml

[FLINK-37866] Migrate glue schema registry e2e test to use aws-kinesis-streams connector
Ran IT Test locally and verified test pass:
```
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (end-to-end-tests) @ flink-formats-json-glue-schema-registry-e2e-tests ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.flink.glue.schema.registry.test.json.GlueSchemaRegistryJsonKinesisITCase
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.263 s - in org.apache.flink.glue.schema.registry.test.json.GlueSchemaRegistryJsonKinesisITCase
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests …
```

[FLINK-37866] Migrate glue schema registry e2e test to use aws-kinesis-streams connector
