README.md

Adding the project README
* Adding the project README
* Tested the clone and build command locally

[FLINK-29439] Add project README

---

flink-sql-connector-dynamodb/pom.xml
flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE

Update NOTICE file to include bundled dependencies for SQL connector
Build locally and verified NOTICE file in target folder

[FLINK-29246][Connectors/DynamoDB] Update NOTICE file for SQL connector

---

flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/examples/SinkIntoDynamoDb.java

Improve DynamoDB Connector Sample Code (https://lists.apache.org/thread/lhvhsyrl3o88lsb6so8158nz6qogsqvn)
* Moved conversion to DDB types from Map function to Element Converter
Run `SinkIntoDynamoDb` locally

[FLINK-29954][Connectors/DynamoDB] Improve DynamoDB Connector Sample Code

---

README.md

Updating README to align the name change from DynamoDB to AWS.

[FLINK-29960] Update Readme for name change.

---

.github/workflows/ci.yml

- Fix Flink 1.15/1.16 CI build
- Verified in PR actions

[hotfix][Connectors/AWS] Fix Flink configuration in CI build

---

.idea/vcs.xml
docs/content.zh/docs/connectors/datastream/dynamodb.md
docs/content.zh/docs/connectors/table/dynamodb.md
docs/content/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/table/dynamodb.md

- Add documentation for DynamoDB sink 
- Manually copied into the `flink-web` project and built from source
* Dependencies (does it add or upgrade a dependency): no
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
* The serializers: no
* The runtime per-record code paths (performance sensitive): no
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
* Does this pull request introduce a new feature? no
* If yes, how is the feature documented?

[FLINK-25859][Connectors/DynamoDB][docs] DynamoDB sink documentation

---

docs/content.zh/docs/connectors/datastream/dynamodb.md
docs/content.zh/docs/connectors/datastream/firehose.md
docs/content.zh/docs/connectors/datastream/kinesis.md
docs/content.zh/docs/connectors/table/dynamodb.md
docs/content.zh/docs/connectors/table/firehose.md
docs/content.zh/docs/connectors/table/kinesis.md
docs/content/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/datastream/firehose.md
docs/content/docs/connectors/datastream/kinesis.md
docs/content/docs/connectors/table/dynamodb.md
docs/content/docs/connectors/table/firehose.md
docs/content/docs/connectors/table/kinesis.md

Copy over documentation for Kinesis and Firehose from the Flink repo

[FLINK-29907] Externalize Kinesis/Firehose documentation

---

flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisITCase.java

[FLINK-30224](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-30224)
- An IT test was added which ensures that the issue with a slow KDS consumer initialization doesn't cause an NPE during cancelation;
- Previously the issue itself was fixed in [FLINK-29324](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-29324).
Improvement. An IT test was added which checks this fix: [FLINK-29324](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-29324)
This change only adds a new test. Azure build succeeded.
- Dependencies (does it add or upgrade a dependency): **No**
- The public API, i.e., is any changed class annotated with @Public(Evolving): **No**
- The serializers: **No**
- The runtime per-record code paths (performance sensitive): **No**
- Anything that affects …

[FLINK-30224][Connectors/Kinesis] An IT test for slow FlinKinesisConsumer's run() which caused an NPE in close

---

docs/data/dynamodb.yml
docs/data/firehose.yml
docs/data/kinesis.yml

The updated shortcode proposed in FLINK-30378 allows the connector to provide the sql connector data.

[FLINK-30378][docs] Use modified sql_connector_download_table shortcode

---

.github/workflows/push_pr.yml

Update Flink version in CI workflow after Flink release as Flink 1.16.0 is no longer available [in release dist repo](https://dist.apache.org/repos/dist/release/flink/)
This change was verified by build on commit push.

[hotfix][ci] Update Flink version in CI workflow to 1.16.1

---

.github/PULL_REQUEST_TEMPLATE.md

Fix typo in pull request template
*(Please check any boxes [x] if the answer is "yes" )*

[hotfix][Connectors/AWS] fix typo in pull request template

---

NOTICE
flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE

Update current year in NOTICE files

[hotfix][Connectors/AWS] Update current year in NOTICE files

---

flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/sink/throwable/AWSExceptionClassifierUtil.java
flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/sink/throwable/AWSExceptionHandler.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/sink/throwable/AWSExceptionClassifierUtilTest.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/sink/throwable/AWSExceptionHandlerTest.java
flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/AWSFirehoseExceptionClassifiers.java
flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java
flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/AWSFirehoseExceptionClassifiersTest.java

Add support for exception classification based on AWS error codes:
- Add AWSExceptionClassifierUtil to create FatalExceptionClassifiers to classify AWSServiceExceptions
based on AWSErrorDetails error code.
- Add AWSExceptionHandler to provide improved semantics over FatalExceptionClassifier.
Add exception classification based on AWS error codes for the AWS Firehose sink:
- Move Firehose sink exception classifiers into their own class: AWSFirehoseExceptionClassifiers.
- Add FatalExceptionClassifiers for FirehoseExceptions with errorCode "NotAuthorized" and "AccessDeniedException".
- If yes, …

[Flink 31492][Connectors/AWS] Add support for exception classification based on AWS error codes

---

.github/workflows/nightly.yml
.github/workflows/push_pr.yml

- Update CI workflows to include Flink 1.17.0 in PR build and 1.18-SNAPSHOT in nightly builds
- Use archive.apache.org for downloading binaries in line with other connectors
This change was verified by build on commit push.

[hotfix][ci] Update Flink versions in CI builds

---

docs/content.zh/docs/connectors/datastream/dynamodb.md
docs/content.zh/docs/connectors/datastream/firehose.md
docs/content.zh/docs/connectors/datastream/kinesis.md
docs/content.zh/docs/connectors/table/dynamodb.md
docs/content.zh/docs/connectors/table/firehose.md
docs/content.zh/docs/connectors/table/kinesis.md
docs/content/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/datastream/firehose.md
docs/content/docs/connectors/datastream/kinesis.md
docs/content/docs/connectors/table/dynamodb.md
docs/content/docs/connectors/table/firehose.md
docs/content/docs/connectors/table/kinesis.md
docs/data/dynamodb.yml
docs/data/firehose.yml
docs/data/kinesis.yml

*Short code related to externalized connector retrieve version from its own data yaml.*

[FLINK-32024][docs] Short code related to externalized connector retrieve version from its own data yaml

---

flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriter.java
flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriterTest.java

Addressing performance regression observed in kinesis sink in FLINK-31772.

[FLINK-31772] Adjusting Kinesis Ratelimiting strategy to fix performance regression

---

flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
pom.xml

Update dependency versions for guava and snappy-java
- Updated version in POM
- Updated NOTICE file for `flink-sql-connector-kinesis`

[FLINK-32500][Connectors/AWS] Update dependency versions for guava and snappy-java

---

flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/src/test/java/org/apache/flink/connector/firehose/table/test/KinesisFirehoseTableITTest.java
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/src/test/java/org/apache/flink/connector/kinesis/table/test/KinesisStreamsTableApiIT.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/java/org/apache/flink/streaming/kinesis/test/KinesisTableApiITCase.java
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/src/test/java/org/apache/flink/streaming/kinesis/test/model/Order.java
flink-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/testutils/KinesisFirehoseTestUtils.java
flink-connector-aws-kinesis-streams/pom.xml
flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/reader/PollingKinesisShardSplitReader.java
flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/examples/SinkIntoKinesis.java
flink-connector-dynamodb/pom.xml
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriter.java
flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactory.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkITCase.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriteRequestTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriterStateSerializerTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/DynamoDbDynamicSinkFactoryTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataToAttributeValueConverterTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/DynamoDbSerializationUtilTest.java
flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/PrimaryKeyBuilderTest.java
flink-connector-kinesis/src/main/resources/META-INF/NOTICE
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/KinesisPubsubClient.java
flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcherForShardConsumerException.java
flink-sql-connector-aws-kinesis-streams/src/main/resources/META-INF/NOTICE
pom.xml
tools/maven/checkstyle.xml

- Remove the dependency on [flink-shaded](https://issues.apache.org/jira/browse/FLINK-shaded) for [flink-connector-aws](https://github.com/apache/flink-connector-aws)
- Remove Guava dependency from DDB connector
- Update NOTICE files
This is an update to https://github.com/apache/flink-connector-aws/pull/75

[FLINK-32208] Remove dependency on flink-shaded from flink-connector-aws 

---

flink-connector-aws-base/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-streams/pom.xml
flink-connector-aws/flink-connector-dynamodb/pom.xml
flink-connector-aws/flink-connector-kinesis/pom.xml
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws/flink-sql-connector-aws-kinesis-streams/pom.xml
flink-connector-aws/flink-sql-connector-dynamodb/pom.xml
pom.xml

Change groupId for flink-connector-parent.
This change is already covered by existing tests

[FLINK-30470][build] Change groupId for flink-connector-parent

---

.github/workflows/common.yml

Prevent AWS E2E tests running on PR

[FLINK-33279][Connector/Kinesis] Do not run AWS e2e tests on PR

---

flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
pom.xml

Update AWS SDKv2 to v2.20.144
Reorder NOTICE files for consistency

[FLINK-32230][Connectors/AWS] Update AWS SDKv2 to v2.20.144

---

flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/source/split/KinesisShardSplit.java

[FLINK-33194] Remove dependency on Flink Shaded
This change is already covered by existing tests.

[FLINK-33194][Connectors/Kinesis] Remove dependency on Flink Shaded

---

docs/content.zh/docs/connectors/datastream/kinesis.md
docs/content/docs/connectors/datastream/kinesis.md

Resolve uid collision between 2 tab containers in Kinesis connector doc to fix behavior when switching between tabs: currently top container (`GlueSchemaRegistryJsonDeserializationSchema`) is activated when tab with `AvroDeserializationSchema` is selected under [The DeserializationSchema](https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/connectors/datastream/kinesis/#the-deserializationschema).
Building documentation locally.

[hotfix][docs] Fix identifier collision causing coflict when switching between tabs in kinesis connector docs

---

docs/data/dynamodb.yml
docs/data/firehose.yml
docs/data/kinesis.yml

* Promoting v4.2.0 docs to final and including Flink compatibility matrix

[hotfix][Connectors/AWS] Promoting v4.2.0 docs to final and including Flink compatibility matrix

---

docs/content.zh/docs/connectors/datastream/dynamodb.md
docs/content/docs/connectors/datastream/dynamodb.md

[FLINK-34017] Connectors docs with 404 link in dynamodb.md

---

NOTICE
flink-connector-aws/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-aws-kinesis-streams/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
flink-connector-aws/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE

[hotfix] Set copyright year to 2024

---

flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java

Tests that use `FakeKinesisFanOutBehavioursFactory` occasionally run into issue while creating mock for Kinesis shard subscription:
```
java.lang.ClassCastException: org.mockito.codegen.Subscription$MockitoMock$1959866534 cannot be cast to org.reactivestreams.Subscription
```
This failure leads to `TimeoutException` in `FanOutShardSubscriber`, resulting in workflow timing out due to continuous retries.
Using fake subscription implementation instead of Mockito mock to resolve this issue.
This change is already covered by existing tests and can be verified by running project build in Github Actions.

[FLINK-34407][Connectors/Kinesis] Fix unstable test

---

flink-connector-aws/flink-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriterTest.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriterTest.java
flink-connector-aws/flink-connector-dynamodb/pom.xml
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSink.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
flink-connector-aws/flink-connector-kinesis/pom.xml
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
flink-formats-aws/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroSchemaCoderTest.java
flink-formats-aws/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryInputStreamDeserializerTest.java
flink-formats-aws/flink-json-glue-schema-registry/pom.xml
flink-formats-aws/flink-json-glue-schema-registry/src/main/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSchemaCoderProvider.java
flink-formats-aws/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonDeserializationSchemaTest.java
pom.xml

- Update DynamoDBSink, KinesisFirehoseSink, and KinesisStreamsSink to be compatible with updated SinkV2 interfaces
- Resolve dependency convergence issues
This change is already covered by existing tests.
Additional verification:
- Successful CI run with `1.19-SNAPSHOT`: https://github.com/z3d1k/flink-connector-aws/actions/runs/7733977237/job/21090289596

[FLINK-34260][Connectors/AWS] Update flink-connector-aws to be compatible with updated SinkV2 interfaces

---

.github/workflows/nightly.yml
.github/workflows/push_pr.yml

Update Flink version list in CI configuration following 1.19.0 release

[hotfix][Connectors/AWS] Update Flink versions in CI

---

flink-connector-aws/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkElementConverter.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkElementConverter.java
flink-connector-aws/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkElementConverterTest.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbBeanElementConverter.java
flink-connector-aws/flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbBeanElementConverterTest.java

This is a minor PR to remove lazy initialisation of DynamoDbbeanElementConverter, KinesisSinkStreamsElementConverter, KinsesisFirehoseElementConverter.

[FLINK-30388] Move Lazy Initialization of AWS element converters to SinkWriter open() method

---

flink-connector-aws/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
flink-connector-aws/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java

Perform snapshot state even after source operator had been cancelled.
This solves the issue when operator state is not being saved during stor-with-savepoint workflow.

[FLINK-35115][Connectors/Kinesis] Allow kinesis consumer to snapshotState after operator had been cancelled

---

flink-connector-aws/flink-connector-kinesis/pom.xml

Add `org.apache.flink.connector.aws.sink` to relocation list in order to prevent class conflicts while including `flink-connector-kinesis` alongside with `flink-connector-aws-kinesis-firehose`.
- Manually verified by running the Kinesis connector and Firehose sink on a local Flink cluster.
- Verified build artifacts

[FLINK-35559][Connector/Kinesis] fix shading configuration to avoid class conflicts when using flink-connector-kinesis alongside Firehose sink

---

.github/workflows/nightly.yml
.github/workflows/push_pr.yml

Update ci build configuration after 1.20.0 release
This change is already covered by Github approval workflow.

[hotfix][ci] Update ci to include 1.20.0

---

flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitGraphInconsistencyTracker.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/enumerator/tracker/SplitTracker.java

…lits
Removing dependency on sorting of splits. This also makes sure that if parent and child come in same describestream call, we get TRIM_HORIZON for the child instead of race conditions where parent and child both get assigned LATEST shard iterator
This change is already covered by existing tests,

[FLINK-36215][dynamodb][BugFix] Removing dependency on sorting of splits

---

flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSClientUtil.java
flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSClientUtilTest.java
flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/DynamoDbStreamsSource.java

Adding support for custom override configuration in AWSClientUtil.java

[FLINK-36206][Connectors/AWS] Adding support for custom override configuration

---

flink-connector-aws/flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/source/DynamoDbStreamsSource.java

DDB Connector is not retrying all SDK exceptions. Changing the retry strategy to SDK default adaptive strategy to fix this
This change is already covered by existing tests,
*(example:)*
- *Added integration tests for end-to-end deployment*

[FLINK-36329][Connectors/DynamoDB] Changing retry strategy to use SDK retries to catch all retryable exceptions

---

docs/data/dynamodb.yml
docs/data/firehose.yml
docs/data/kinesis.yml
flink-connector-aws-base/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-firehose-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-kinesis-streams-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-aws-sqs-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-connector-kinesis-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-formats-avro-glue-schema-registry-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/flink-formats-json-glue-schema-registry-e2e-tests/pom.xml
flink-connector-aws-e2e-tests/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws/flink-connector-aws-kinesis-streams/pom.xml
flink-connector-aws/flink-connector-dynamodb/pom.xml
flink-connector-aws/flink-connector-kinesis/pom.xml
flink-connector-aws/flink-connector-sqs/pom.xml
flink-connector-aws/flink-sql-connector-aws-kinesis-firehose/pom.xml
flink-connector-aws/flink-sql-connector-aws-kinesis-streams/pom.xml
flink-connector-aws/flink-sql-connector-dynamodb/pom.xml
flink-connector-aws/flink-sql-connector-kinesis/pom.xml
flink-connector-aws/pom.xml
flink-formats-aws/flink-avro-glue-schema-registry/pom.xml
flink-formats-aws/flink-json-glue-schema-registry/pom.xml
flink-formats-aws/pom.xml
flink-python/pom.xml
pom.xml

Bump version to `5.1-SNAPSHOT`

[FLINK-36668][build] Update AWS build for v5.0

---

docs/content/docs/connectors/table/kinesis.md

[hotfix][docs] Fix description of new configuration table
